all:
  children:
    proxmox:
      hosts:
        proxmox-01:
          ansible_host: 192.168.10.10
    jumpbox:
      hosts:
        px-jump-01:
          ansible_host: 192.168.10.20
    k3s_servers:
      hosts:
        k3s-server-01:
          ansible_host: 192.168.10.31
        k3s-server-02:
          ansible_host: 192.168.10.32
        k3s-server-03:
          ansible_host: 192.168.10.33
    k3s_agents:
      hosts:
        k3s-agent-01:
          ansible_host: 192.168.10.41
        k3s-agent-02:
          ansible_host: 192.168.10.42
        k3s-agent-03:
          ansible_host: 192.168.10.43
