apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kong.yaml
  - cert-manager.yaml
  - cluster-issuers.yaml
  - metallb.yaml
  - victoria-metrics.yaml
  - loki.yaml
  - tempo.yaml
  - vault.yaml
  - external-secrets.yaml
  - secret-stores.yaml
